---
title: "Problem 6.6a part 1"
output: html_notebook
---

6.6A database has five transactions. Let minsup=60% and minconf=80%.
(a)  Find all frequent itemsets using Apriori and FP-growth, respectively. Compare the efficiency of the two mining processes.

TIDitemsbought
T100{M, O, N, K, E, Y}
T200{D, O, N, K, E, Y}
T300{M, A, K, E}
T400{M, U, C, K, Y}
T500{C, O, O, K, I, E}

Apriori
```{r}
#Apriori
TID <- list(c("M","O","N","K","E","Y"),c("D","O","N","K","E","Y"),c("M","A","K","E"),c("M","U","C","K","Y"),c("C","O","O","K","I","E"))
TID_Header <- c("T100","T200","T300","T400","T500")

summary(TID)

#install.packages("arules", dependencies=TRUE)
library(arules)
library(Matrix)

#TID <- gsub("\"","",TID)
TID

results<-apriori(TID,parameter=list(supp=.6, conf=.8, target="rules"))

inspect(results)

#library(arulesViz)
#plot(results)
#plot(results, method = "grouped", control = list(k = 5))
#plot(results, method="graph", control=list(type="items"))
#plot(results, method="paracoord",  control=list(alpha=.5, reorder=TRUE))
#plot(results,measure=c("support","lift"),shading="confidence")
```

FP-Growth 
```{r}
#FP-growth

#install.packages("arulesCBA", dependencies = TRUE)
library(arulesCBA)

#results2 =  CBA(Species ~ Sepal,data = TID, supp = 0.6, conf = 0.8)

#predictions <- rCBA::classification(train,rules)
#table(predictions)
#sum(as.character(train$Species)==as.character(predictions),na.rm=TRUE)/length(predictions)
#prunedRules <- rCBA::pruning(train, rules, method="m2cba", parallel=FALSE)
#predictions <- rCBA::classification(train, prunedRules)
#table(predictions)
#sum(as.character(train$Species)==as.character(predictions),na.rm=TRUE)/length(predictions)
```

Compare the efficiency of the two mining processes:
###

